name: build
on: [push, pull_request]

jobs:
  programming-1-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./programming/assignment1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Test
        run: poetry run python -m pytest

  programming-1-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./programming/assignment1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Lint
        run: |
          poetry run python -m pylint scripts
          poetry run python -m black **/*.py --check
          poetry run python -m mypy **/*.py
